version: '3'
services:
  mongo:
    image: mongo:3.6.18-xenial
    restart: always
    ports:
      - "27017:27017"
    network_mode: host
    volumes:
      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"

  springyrdyrdocker:
    build: springtestedocker/
    image: springtestedocker
    depends_on:
      - mongo
    network_mode: "host"
    hostname: localhost
    restart: always
    ports:
      - "8082:8082"
    healthcheck:
      test: "exit 0"
